# -*- coding: utf-8 -*-
"""Retailsales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W2xswe5URwttSlQAacTbPvCi0VUiOr9C
"""

import pandas as pd

df = pd.read_csv("retail_clean.csv")

print(df.columns)

print(df['sub_category'].value_counts().head())

df[['quantity', 'profit']].corr()

import seaborn as sns
import matplotlib.pyplot as plt

sns.scatterplot(data=df, x='quantity', y='profit')
plt.title('Inventory Quantity vs Profit')
plt.show()

df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')
df['month'] = df['order_date'].dt.month

df.groupby('month')['profit'].sum()

df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.to_csv("retail_final.csv", index=False)

df.to_csv("retail_final.csv", index=False)

"""Inventory vs Profit Insight

The correlation between inventory quantity and profit is (positive/negative).

This indicates that increasing inventory (helps / hurts) profitability.

Overstocking low-performing products leads to capital lock-in and reduced margins.

Seasonality Insight

Profit peaks during Month X, Y.

Lowest profitability is observed during Month Z.

This suggests seasonal stocking strategy rather than uniform inventory levels
"""